server:
  port: 8080
  shutdown: graceful

psrpc:
  zk:
    server: localhost:2181
    root: psrpc
  app:
    id: psrpc
    namespace: public
    env: dev
    version: 1.0.0
  provider:
    metas:
      dc: 'bj'
      gray: 'false'
      unit: 'B001'
      tc: 20

psregistry:
  servers: http://localhost:8484

# apollo config
app:
  id: psrpc
apollo:
  cacheDir: /config/data/                       #配置本地配置缓存目录
  cluster: default                              #指定使用哪个集群的配置
  meta: http://localhost:9080                   #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true      #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                               #是否开启 Apollo
    namespaces: application                            #设置 Namespace
    eagerLoad:
      enabled: false                            #将 Apollo 加载提到初始化日志系统之前

logging:
  level:
    root: error
    cn.pengshao.rpc: info