server:
  port: 8080
  shutdown: graceful

psrpc:
  zk:
    server: localhost:2181
    root: psrpc
  app:
    id: psrpc
    namespace: public
    env: dev
    version: 1.0.0
  provider:
    metas:
      dc: 'bj'
      gray: 'false'
      unit: 'B001'

logging:
  level:
    root: error
    cn.pengshao.rpc: info