server:
  port: 8080
  shutdown: graceful

psrpc:
  zkServer: localhost:2181
  zkRoot: psrpc

app:
  id: psrpc
  namespace: public
  env: dev
  version: 1.0.0
  metas: "{dc: 'bj', gray: 'false', unit: 'B001'}"

logging:
  level:
    root: error
    cn.pengshao.rpc: info