server:
  port: 8088

psrpc:
  providers: "http://localhost:8080,http://localhost:8081,http://localhost:8082"
  zkServer: localhost:2181
  zkRoot: psrpc

app:
  id: psrpc
  namespace: public
  env: dev
  version: 1.0.0

logging:
  level:
    root: error
    cn.pengshao.rpc: info