server:
  port: 8088

psrpc:
  zkServer: localhost:2181
  zkRoot: psrpc

app:
  id: psrpc
  namespace: public
  env: dev
  version: 1.0.0
  retries: 2
  timeout: 1000
  grayRatio: 30
  faultLimit: 10
  halfOpenInitialDelay: 10000
  halfOpenDelay: 60000

logging:
  level:
    root: error
    cn.pengshao.rpc: debug